#!/bin/bash
# This script comes with no warranty …use at own risk
# Copyright (C) 2014  Mike Krüger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program or from the site that you downloaded it
# from; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307   USA
#
# my personal Arch Linux Installation script 
# Version Alpha 2

RESULT=0
COUNTER=0
CHOISE_ARRAY=''
HDD_NAME=''
TOTAL_HDD_SIZE=''
TOTAL_RAM_SIZE=''
SWAP_SIZE=''
ROOT_SIZE=''
HOME_SIZE=''
BOOT_SIZE=200
HOSTNAME='r2d2'
LANGUAGE="de_DE"
KEYMAP="de-latin1"
TIMEZONE="Europe/Berlin"
ARCH=''
ARCH_ROOT='/mnt'
USERNAME=''
PID=0

function message_print() {
  if [ "$1" = 1 ]
  then
    # green
    color="32"
  else
    # red
    color="31"
  fi
  
  printf "\033[0;${color}m**$2**\033[m \n"
  return 0
}


function question_yesno() {
  while true; do
    read -p "$1" yn
    case $yn in
      [Yy]* ) RESULT=1; break;;
      [Nn]* ) RESULT=0; break;;
      * ) echo "Please answer yes or no.";;
    esac
  done
  return 0
}

function choise_menu() {
  for i in "${CHOISE_ARRAY[@]}"
  do
    COUNTER=$(( $COUNTER + 1 ))
    echo '['$COUNTER'] '$i
  done
  
  while true; do
    read -p "Make your choise |1|2|3... " number
    if [ "$number" -ge 1 -a "$number" -le $COUNTER ];
    then
      RESULT=$number
      break
    else
      message_print 0 "Please select a valid number!"
    fi
  done
  return 0
}


function stop_spinner() {
  kill -s SIGHUP $PID &
  { wait $PID; } &> /dev/null
  PID=0
}

function start_spinner() {
  setterm -cursor off
  parts=( "|" "/" "-" "\\" )

  while [ 1 ];
  do
    for ix in 0 1 2 3; 
    do
     echo -en ${parts[$ix]}
     sleep .1
     echo -en "\b"
    done
  done
}

function spinner()  {
  if [ $1 == "start" ];
  then
   if [ $PID -eq 0 ];
   then
   start_spinner&
   PID=$!
   fi
  elif [ $1 == "stop" ];
  then
   if [ $PID -ne 0 ];
   then
   stop_spinner
   fi
  fi
}


function first_choise() {
  clear
  echo "************************************************"
  echo "************************************************"
  echo "*********                             **********"
  echo "*********      ARCH FIX 2014          **********"
  echo "*********                             **********"
  echo "********* A ARCH INSTALLATION SCRIPT  **********"
  echo "*********                             **********"
  echo "*********        CREATED BY           **********"
  echo "*********        MEMORYLEAKY          **********"
  echo "*********                             **********"
  echo "************************************************"
  echo "************************************************"
  echo ""
  message_print 0 "This script comes with no warranty …use at own risk"

  echo ""
  echo "Whitch Step you want to execute now"
  CHOISE_ARRAY[0]="The first part partitioned your hard drive and install the base system"
  CHOISE_ARRAY[1]="The second part install all packages (xfce,cups,lightdm...) you need to have a good desktop experience"
  choise_menu
  if [ $RESULT -eq 1 ]
  then
   partitioning
   install_base
  else
   optimize_mirrorlist
   install_yaourt
   adduser
   install_powerpill
  fi

  #clean
  CHOISE_ARRAY=''
  return 0
}

function get_total_hdd_size() {
  TOTAL_HDD_SIZE=$(fdisk -l $1 |grep "Disk "$1":" | head -n 2 | tail -n 1 | cut -d " " -f 5)
  TOTAL_HDD_SIZE=$(($TOTAL_HDD_SIZE / 1024))
  #HDD SIZE IN MB
  TOTAL_HDD_SIZE=$(($TOTAL_HDD_SIZE / 1024))
  return 0
}

function get_total_ram_size() {
  TOTAL_RAM_SIZE=$(grep MemTotal /proc/meminfo | awk '{print $2}')
  #RAM SIZE IN MB
  TOTAL_RAM_SIZE=$(($TOTAL_RAM_SIZE / 1024))
  return 0
}

function calc_optimal_swap_size() {
  get_total_ram_size
  if [ $TOTAL_RAM_SIZE -lt 513 ]
  then
    SWAP_SIZE=$(($TOTAL_RAM_SIZE * 2))
  else
    SWAP_SIZE=$TOTAL_RAM_SIZE
  fi
  return 0
}

function calc_optimal_patition_size() {
  TOTAL_HDD_SIZE=$(($TOTAL_HDD_SIZE - $BOOT_SIZE))
  ROOT_SIZE=$(($TOTAL_HDD_SIZE * 15 / 100))
  HOME_SIZE=$(($TOTAL_HDD_SIZE - $ROOT_SIZE))
  return 0
}

function arch_chroot() {
  arch-chroot $ARCH_ROOT /bin/bash -c "${1}"
}

function partitioning() {
  calc_optimal_swap_size
  echo "On which drive you want to install Arch?"
  eval CHOISE_ARRAY=("/dev/"$(lsblk | grep disk | cut -d" " -f1) )
  choise_menu
  
  
  HDD_NAME=${CHOISE_ARRAY[$RESULT - 1]}
  echo $HDD_NAME
  get_total_hdd_size $HDD_NAME
  calc_optimal_patition_size
  echo '-----------------------'
  echo 'boot: '$BOOT_SIZE ' MB'
  echo 'root: '$ROOT_SIZE ' MB'
  echo 'home: '$HOME_SIZE ' MB'
  echo ''
  echo 'swap: '$SWAP_SIZE ' MB'
  echo '-----------------------'
  
  #Back to KB Sizes
  BOOT_SIZE=$(($BOOT_SIZE * 1024))
  ROOT_SIZE=$(($ROOT_SIZE * 1024))
  HOME_SIZE=$(($HOME_SIZE * 1024))
  SWAP_SIZE=$(($SWAP_SIZE * 1024))

  #Wiping the entire disk
  dd if=/dev/zero of=$HDD_NAME  bs=512  count=1
  
  touch /tmp/fdisk.input
  echo -e "n\np\n1\n\n+"$BOOT_SIZE"K\na\n1\nn\np\n2\n\n+"$SWAP_SIZE"K\nt\n2\n82\nn\np\n3\n\n+"$ROOT_SIZE"K\nn\np\n4\n\n+"$HOME_SIZE"K\nn\np\n5\n\nw" > /tmp/fdisk.input
  
  # Create Partitions
  fdisk $HDD_NAME < /tmp/fdisk.input
  
  # Remove fdisk.input file
  rm /tmp/fdisk.input
  
  mkfs.ext2 -L boot $HDD_NAME'1'
  mkswap -L swap $HDD_NAME'2'
  mkfs.ext4 -L root $HDD_NAME'3'
  mkfs.ext4 -L home $HDD_NAME'4'
  
  #enable swap
  swapon $HDD_NAME'2'
  
  #mount all patitions
  mount $HDD_NAME'3' /mnt
  mkdir /mnt/boot
  mkdir /mnt/home
  mount $HDD_NAME'1' /mnt/boot
  mount $HDD_NAME'4' /mnt/home

  #clean
  CHOISE_ARRAY=''
  return 0
}

function install_base() {
  pacstrap /mnt base base-devel
  genfstab -p /mnt > /mnt/etc/fstab
  echo $HOSTNAME > /mnt/etc/hostname
  echo 'LANG='$LANGUAGE'.UTF-8' > /mnt/etc/locale.conf
  echo 'LC_COLLATE=C' >> /mnt/etc/locale.conf
  echo 'KEYMAP='$KEYMAP > /mnt/etc/vconsole.conf
  arch_chroot 'ln -s /usr/share/zoneinfo/'$TIMEZONE' /etc/localtime'
  arch_chroot 'rm -rf /etc/locale.gen'
  arch_chroot 'touch /etc/locale.gen'
  echo $LANGUAGE'.UTF-8 UTF-8' > /mnt/etc/locale.gen

  #Set locales
  #Steam workaround
  if [ $LANGUAGE = "en_US" ]
  then
    echo "OK!"
  else
    echo 'en_US.UTF-8 UTF-8' >> /mnt/etc/locale.gen
  fi
  
  #create locales
  arch_chroot 'locale-gen'

  #Install extra system stuff
  arch_chroot "pacman --noconfirm -S networkmanager sudo wpa_supplicant"

  #enable NetworkManager
  arch_chroot 'systemctl enable NetworkManager.service'
  
  #enable mutilib
  MULTILIB=''
  ARCH=$(uname -m)
  if [ $ARCH = "x86_64" ]
  then
   MULTILIB=`grep -n "\[multilib\]" /mnt/etc/pacman.conf | cut -f1 -d:`
    if [ -z $MULTILIB ]
    then
      echo -e "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /mnt/etc/pacman.conf
    else
      sed -i "${MULTILIB}s/^#//" /mnt/etc/pacman.conf
      local MULTILIB=$(( $MULTILIB + 1 ))
      sed -i "${MULTILIB}s/^#//" /mnt/etc/pacman.conf
    fi
  fi
  
  arch_chroot 'pacman -Syy'
  
  #create Linux Kernel
  arch_chroot 'mkinitcpio -p linux'

  #configure Clock
  arch_chroot "hwclock --systohc --utc"

  #accountsservice Lightdm bugFix
  arch_chroot "pacman --noconfirm -S accountsservice"

  #Enable Grub
  arch_chroot 'pacman --noconfirm -S grub'
  echo "" >> /mnt/etc/default/grub
  echo "# fix broken grub.cfg gen" >> /mnt/etc/default/grub
  echo "GRUB_DISABLE_SUBMENU=y" >> /mnt/etc/default/grub
  arch_chroot 'grub-install --target=i386-pc --recheck --debug '${HDD_NAME}
  arch_chroot 'grub-mkconfig -o /boot/grub/grub.cfg'
  
  #SET Root password
  arch_chroot 'passwd'
  
  umount $HDD_NAME'1'
  umount $HDD_NAME'3'
  umount $HDD_NAME'4'

  reboot #<< end
  return 0
}

function optimize_mirrorlist() {
  clear
  echo "******************************************************"
  echo "*************** optimizing mirrorlist! ***************"
  echo "******************************************************"
  echo ""
  message_print 0 "******************************************************"
  message_print 0 "*******please wait, this will take a few minutes!*****"
  message_print 0 "******************************************************"
  echo ""

  TFILE="/tmp/mirrorlist.tmp"
  CCODE=${LANGUAGE:3:2}
  URL="https://www.archlinux.org/mirrorlist/?country=${CCODE}&use_mirror_status=on"

  curl -so ${TFILE} ${URL}
  sed -i 's/^#Server/Server/g' ${TFILE}

  spinner "start"
  rankmirrors -n 6 $TFILE > /etc/pacman.d/mirrorlist
  sed -i '/^#/ d' /etc/pacman.d/mirrorlist
  spinner "stop"

  pacman -Syy
  return 0
}

function install_yaourt() {
  clear
  echo "******************************************************"
  echo "***************   Installing YAOURT!   ***************"
  echo "******************************************************"
  echo ""

  cd /tmp
  echo "Retrieving package-query ..."
  curl -O https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz
  echo "Retrieving yaourt ..."
  curl -O https://aur.archlinux.org/packages/ya/yaourt/yaourt.tar.gz

  echo "Uncompressing package-query ..."
  tar zxvf package-query.tar.gz
  cd package-query
  echo "Installing package-query ..."
  makepkg -si --asroot --noconfirm

  cd ..

  echo "Uncompressing yaourt ..."
  tar zxvf yaourt.tar.gz
  cd yaourt
  echo "Installing yaourt ..."
  makepkg -si --asroot --noconfirm

  cd ..

  rm -rf package-query
  rm -rf yaourt
  rm -rf package-query.tar.gz
  rm -rf yaourt.tar.gz

  cd
  return 0
}

function install_package() {
  case "$1" in
   "pacman")
    su - ${USERNAME} -c ' pacman --noconfirm -S '$2
    ;;
   "yaourt")
    su - ${USERNAME} -c ' yaourt --noconfirm -S '$2
    ;;
    "powerpill")
    su - ${USERNAME} -c ' powerpill --noconfirm -S '$2
    echo  ""
    ;;
   *)
    echo ''
    ;;
  esac

  return 0
}

function adduser() {
  clear
  echo "******************************************************"
  echo "***************      Add USER!         ***************"
  echo "******************************************************"
  echo ""
  read -p "Enter username : " USERNAME
  useradd -m -g users -G audio,lp,network,optical,scanner,storage,sys,video,power,wheel -d /home/$USERNAME -s /bin/bash $USERNAME
  echo ""
  message_print 0 "******************************************************"
  message_print 0 "*****please enter a secure password for the user!*****"
  message_print 0 "******************************************************"
  echo ""
  passwd $USERNAME

  ## Uncomment to allow members of group wheel to execute any command
  sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /etc/sudoers
  return 0
}

function install_powerpill() {
  clear
  echo "******************************************************"
  echo "***************  Installing POWERPILL! ***************"
  echo "******************************************************"
  echo ""
  install_package "yaourt" "powerpill"
  reflector -p rsync -f n -l m
  powerpill -Syu
  return 0
}

first_choise

